### ISSUE TITLE
How to cite the SEM book?

### ISSUE THREAD

**Issue by seanhardison1** [jslefche/sem_book#4]
Are there plans in the works to get a DOI for the book or the repository? Do you know of any papers citing the work? 

I find myself using this book quite a bit and want to be sure you're properly credited!

**Comment by jslefche** [comment]
This is a good question. It’s a work in progress and still missing large chunks (eg, confirmatory factor analysis, instrumental variable analysis, an intro to the method, its philosophy, and causality). Plus there is new work that needs to be integrated from Bill Shipley and Bob Douma’s papers. So I guess I am open to ways to archive and acquire a DOI while also allowing the material to remain fluid

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

From: Sean ***@***.***>
Sent: Friday, October 15, 2021 10:50 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [jslefche/sem_book] How to cite the SEM book? (#4)

External Email - Exercise Caution

Are there plans in the works to get a DOI for the book or the repository? Do you know of any papers citing the work?

I find myself using this book quite a bit and want to be sure you're properly credited!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjslefche%2Fsem_book%2Fissues%2F4&data=04%7C01%7Clefcheckj%40si.edu%7C08730ddc817644c2ae6a08d98feb2c79%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637699062502958295%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wI4%2BoiWNO3vrSWVtn%2Fj5DT%2BK%2F7SNjN7BwCM0%2BM%2Ffm68%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAR4AV2J76UKFOOP5ZFUPS3UHA5UNANCNFSM5GCERZCQ&data=04%7C01%7Clefcheckj%40si.edu%7C08730ddc817644c2ae6a08d98feb2c79%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637699062502968251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lnsiXlFymazMXb9C9l0O7bvyiquyJra%2B%2BcbMx23%2BraE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clefcheckj%40si.edu%7C08730ddc817644c2ae6a08d98feb2c79%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637699062502968251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Qr4YggMo2HMsvxLrPoXFrfdZt2CIl3VoTtm7lWcdCfo%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clefcheckj%40si.edu%7C08730ddc817644c2ae6a08d98feb2c79%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637699062502978197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M5DrSgIgtX0z1YSIeNgq2IKEHnZcVxIt2InLOgxUdFQ%3D&reserved=0>.

**Comment by seanhardison1** [comment]
Hmmm it seems like you could generate a DOI and associate it with a release [through zenodo](https://guides.github.com/activities/citable-code/). [This guide](https://genr.eu/wp/cite/) suggests that your first release linked to Zenodo would establish a global DOI that would be versioned with future releases. Might be worth looking into
